// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"go_zero-crud/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/companies/create",
				Handler: CreateCompanyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/companies/id/:id",
				Handler: GetCompanyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/create",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/id/:id",
				Handler: GetUserHandler(serverCtx),
			},
		},
	)
}
