// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_service.proto

package server

import (
	"context"

	"go_zero-crud/rpc/service/user_service/internal/logic"
	"go_zero-crud/rpc/service/user_service/internal/svc"
	"go_zero-crud/rpc/service/user_service/pb/user_service"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user_service.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *user_service.UserRequest) (*user_service.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServiceServer) CreateUser(ctx context.Context, in *user_service.UserRequest) (*user_service.EmptyResponse, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}
