// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: company_service.proto

package server

import (
	"context"

	"go_zero-crud/rpc/service/company_service/internal/logic"
	"go_zero-crud/rpc/service/company_service/internal/svc"
	"go_zero-crud/rpc/service/company_service/pb/company_service"
)

type CompanyServiceServer struct {
	svcCtx *svc.ServiceContext
	company_service.UnimplementedCompanyServiceServer
}

func NewCompanyServiceServer(svcCtx *svc.ServiceContext) *CompanyServiceServer {
	return &CompanyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CompanyServiceServer) GetCompany(ctx context.Context, in *company_service.CompanyRequest) (*company_service.CompanyResponse, error) {
	l := logic.NewGetCompanyLogic(ctx, s.svcCtx)
	return l.GetCompany(in)
}

func (s *CompanyServiceServer) CreateCompany(ctx context.Context, in *company_service.CompanyRequest) (*company_service.EmptyResponse, error) {
	l := logic.NewCreateCompanyLogic(ctx, s.svcCtx)
	return l.CreateCompany(in)
}
